
# 1. Find the name of all songs longer than 3 minutes
SELECT title AS song_name
FROM Song
WHERE duration > 180;

# 2. Find the name and number of streams for the most listened to song for the user named ‘Ambrosia Lock’
SELECT title AS top_song,
    count(title) AS streams
FROM account, listener, listening_event, song
WHERE account.full_name = 'Ambrosia Lock'
AND account.account_id = listener.listener_id
AND listener.listener_id = listening_event.listener_id
AND listening_event.song_id = song.song_id
GROUP BY song.song_id
ORDER BY streams DESC
LIMIT 1;

# 3. Find the titles, artists and number of streams of the top 3 most streamed songs
SELECT title as song_name,
    account.full_name as artist_name,
    COUNT(listening_event.song_id) as streams
FROM account, artist, song, listening_event
WHERE account.account_id = artist.artist_id
AND artist.artist_id = song.artist_id
AND song.song_id = listening_event.song_id
GROUP BY song.song_id, song.title, account.full_name
ORDER BY streams DESC
LIMIT 3;

# 4. Find the total revenue generated by each subscription plan
SELECT subscription_plan.plan_name,
    COUNT(billing_event.plan_id) * subscription_plan.monthly_price AS revenue
FROM subscription_plan, billing_event
WHERE subscription_plan.plan_id = billing_event.plan_id
GROUP BY subscription_plan.plan_id;

# 5. Show each artist the total number of streams across all their songs
SELECT account.full_name as artist_name,
    COUNT(listening_event.song_id) as total_streams
FROM account, artist, song, listening_event
WHERE account.account_id = artist.artist_id
AND artist.artist_id = song.artist_id
AND listening_event.song_id = song.song_id
GROUP BY account.full_name
ORDER BY total_streams DESC;

# 6. Find the top genre for the listener named ‘Andrea Santos’
SELECT artist.genre AS genre
FROM account, song, artist, listener, listening_event
WHERE account.full_name = 'Andrea Santos'
AND account.account_id = listener.listener_id
AND listening_event.listener_id = listener.listener_id
AND song.artist_id = artist.artist_id
GROUP BY artist.genre
ORDER BY COUNT(artist.genre) DESC
LIMIT 1;

7. Find the average length of a playlist
SELECT AVG(playlist_length) AS avg_playlist_length
FROM (
    SELECT SUM(song.duration) AS playlist_length
    FROM playlist, playlist_song, song
    WHERE playlist.playlist_id = playlist_song.playlist_id
    AND playlist_song.song_id = song.song_id
    GROUP BY playlist.playlist_id
) AS sub;

# 8. Find the number of artists from each country
SELECT country,
    COUNT(artist_id) AS num_artists
FROM artist
GROUP BY country;